add test: list rule with service group
IBM/platform-services-python-sdk pull request #168
Opened 2022-10-07 18:05 UTC by cam-d12

## PR summary
This PR adds CBR support for the new service_group_id parameter in rules.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
No current behavior should be modified. Adds the further control to be able to apply rules to service groups

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2022-10-12 14:19 UTC, soohoowoohoo requested changes

2022-10-12 14:19 UTC, soohoowoohoo commented on test/integration/test_context_based_restrictions_v1.py
> +        assert rule_list is not None
I would expect the tests to assert that 1 rule was returned in the list and that it has the rule ID of the rule created above.

2022-10-13 13:24 UTC, soohoowoohoo requested changes

2022-10-13 13:24 UTC, soohoowoohoo commented on test/integration/test_context_based_restrictions_v1.py
> +        assert rule_list['total_count'] == 1
does the python library support a `total_count` property? I know we have a `count` property but idk if there are any conversions being done somewhere in the python lib.

2022-10-13 13:24 UTC, soohoowoohoo commented on test/integration/test_context_based_restrictions_v1.py
> +        assert rule['id'] == rule_list['first'].id
wouldn't we need to access the `rules` property first and don't python lists take indices like arrays?

2022-10-13 19:53 UTC, cam-d12 commented
@padamstx All integration tets passings but Travis CI build failing due to linting errors. Tried fixing locally and happy to try and other steps to resolve but otherwise I think this PR is good to go.

2022-10-13 19:59 UTC, padamstx commented
Something must have happened with respect to the linter that is being used in our travis builds, because these linting errors look suspiciously like something that the generator would do.  I wonder if a new version of the linter is now complaining about these or something.

@pyrooka would you have any insight here?  All these linter errors seem to have blindsided us :)

2022-10-14 10:48 UTC, pyrooka commented
Okay, I just finished some testing and @padamstx your intuition was good. A recently released Pylint has introduced this "issue". With <2.15.X the project builds fine, but with 2.15.0 and above it throws errors.
I've opened a separate [PR](https://github.com/IBM/platform-services-python-sdk/pull/169) with the fix, so after that get merged, we can update this PR.

2022-10-14 13:53 UTC, soohoowoohoo reviewed
LGTM

2022-10-14 22:06 UTC, padamstx approved these changes
LGTM

2022-10-14 22:10 UTC, merged

2022-10-14 22:14 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.27.1 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-python-sdk/releases/tag/v0.27.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: