feat (user management) update user management sdk with list user api update
IBM/platform-services-python-sdk pull request #198
Opened 2023-04-25 20:45 UTC by PureMathematics

## PR summary

Update Include_settings and substring search functionality (User Management) 

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information
the current issue for updating SDK https://github.ibm.com/IAM/uum/issues/5882 
the previous issue for the user management code change https://github.ibm.com/IAM/uum/issues/4948

2023-04-25 20:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-python-sdk?pullRequest=198) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-python-sdk?pullRequest=198) before we can accept your contribution.<br/><hr/>**David-Lim0305** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-python-sdk?pullRequest=198) it.</sub>

2023-04-26 21:02 UTC, padamstx requested changes
Changes look good except for the same issues as the other PRs:
1. use git commit -s option
2. one code fragment per operation in the examples

Also, please run "make lint-fix" in your sandbox to reformat the source files and then commit those results (see update_service.md).

2023-04-26 21:02 UTC, padamstx commented on examples/test_user_management_v1_examples.py
> +    def test_list_users_example_with_include_settings(self):
one code example per operation :)

2023-04-28 15:51 UTC, PureMathematics commented
integration test
<img width="1679" alt="python-integration" src="https://user-images.githubusercontent.com/35412774/235195004-c8ff0fb4-a840-4043-acd5-9d6a2946c1d8.png">

2023-04-28 15:52 UTC, PureMathematics commented
examples test
<img width="1668" alt="python-example" src="https://user-images.githubusercontent.com/35412774/235195057-e81f9e6c-e490-41d2-bd88-eb8e603595a4.png">

2023-04-28 22:56 UTC, merged

2023-05-31 18:17 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.35.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-python-sdk/releases/tag/v0.35.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: